### ISSUE TITLE
Better way to get rid of hardcoded paths in `main_test.cpp`

### ISSUE THREAD

**Issue by boris-kolpackov** [lyrahgames/build2-happly#2]
I was trying to wrap my head why `main_test.cpp` is generated from a template and when I understood why (to get rid of hardcoded paths to input files), it made me think that there got to be a less heavy-handed way. It would make sense to do this if that's what upstream did (so you could reuse `main_test.cpp` without any modifications). But seeing that you are modifying it, you could just fix it by pass the `sampledata` directory as an argument or some such.

In fact, thinking about it some more, you could actually make the unmodified test work with a `testscript`. I.e., copy (or symlink) the input files in the appropriate location in the test directory so that it matches what's expected by the test.

**Comment by lyrahgames** [comment]
> I was trying to wrap my head why `main_test.cpp` is generated from a template and when I understood why (to get rid of hardcoded paths to input files), it made me think that there got to be a less heavy-handed way. It would make sense to do this if that's what upstream did (so you could reuse `main_test.cpp` without any modifications). But seeing that you are modifying it, you could just fix it by pass the `sampledata` directory as an argument or some such.

Indeed, I didn't really like the solution, either.
The hard coded paths have been an issue in several projects and I wanted to get rid of them as soon as possible.
So, I tried to modify the files as less as possible to make it easier to incorporate future changes.

> In fact, thinking about it some more, you could actually make the unmodified test work with a `testscript`. I.e., copy (or symlink) the input files in the appropriate location in the test directory so that it matches what's expected by the test.

That is a really neat idea.
I addressed this in the last commit and it worked and made it so much easier. Thank you for that. 

I like the testscript language but due to its complexity and my rare use cases, I am still very inexperienced.
If you have time, please, take a look at my solution again.

**Comment by lyrahgames** [comment]
[Here](https://ci.cppget.org/@0aa674e7-efdd-4943-89fc-cb2db80ae4ea) is the new CI build and, unfortunately, it contains more errors.
Now, I remember that I did not only used the `in` module for hard coded paths but also to get rid of wrong char conversions in the tests. I did this in the commits 6e4c4f83d6e35d07302aec4944f83030069d1757 and de634617c6f57c1de1b46ab61969d0de6998d1dd.

**Comment by boris-kolpackov** [comment]
Yes, the `testscript` looks reasonable.

> Now, I remember that I did not only used the in module for hard coded paths but also to get rid of wrong char conversions in the tests.

If you are fixing issues in upstream code, the recommended practice is to symlink the original file as `*.orig`, make a copy of it, and patch the errors. You would also want to submit the fixes upstream. The thinking here is that this is temporary and upstream will hopefully fix the issues. You can see this technique in practice here: https://github.com/build2-packaging/crashpad/commit/b38531041425e0d2fb0af2f5145f2c483dcd938c

**Comment by lyrahgames** [comment]
> If you are fixing issues in upstream code, the recommended practice is to symlink the original file as `*.orig`, make a copy of it, and patch the errors. You would also want to submit the fixes upstream. The thinking here is that this is temporary and upstream will hopefully fix the issues. You can see this technique in practice here: [build2-packaging/crashpad@b385310](https://github.com/build2-packaging/crashpad/commit/b38531041425e0d2fb0af2f5145f2c483dcd938c)

I fixed the issues with this procedure. Thank you! [Here](https://ci.cppget.org/@2c6b9c90-7794-4d52-bddf-5db7d15c5c0c) is the CI run.
As soon as you close the issue, I will submit the new package version and try to make a pull request to the upstream repository.

**Comment by boris-kolpackov** [comment]
LGTM.
